// Copyright 2026 Alibaba Group Holding Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/credentialprovider/v1/credential_provider.proto

package credentialproviderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialResponse_Status int32

const (
	CredentialResponse_STATUS_UNSPECIFIED CredentialResponse_Status = 0
	CredentialResponse_SUCCESS            CredentialResponse_Status = 1
	CredentialResponse_UNAVAILABLE        CredentialResponse_Status = 2
	CredentialResponse_DENIED             CredentialResponse_Status = 3
)

// Enum value maps for CredentialResponse_Status.
var (
	CredentialResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "UNAVAILABLE",
		3: "DENIED",
	}
	CredentialResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCESS":            1,
		"UNAVAILABLE":        2,
		"DENIED":             3,
	}
)

func (x CredentialResponse_Status) Enum() *CredentialResponse_Status {
	p := new(CredentialResponse_Status)
	*p = x
	return p
}

func (x CredentialResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes[0].Descriptor()
}

func (CredentialResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes[0]
}

func (x CredentialResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialResponse_Status.Descriptor instead.
func (CredentialResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_credentialprovider_v1_credential_provider_proto_rawDescGZIP(), []int{1, 0}
}

type CredentialResponse_Encoding int32

const (
	CredentialResponse_ENCODING_UNSPECIFIED CredentialResponse_Encoding = 0
	CredentialResponse_UTF8                 CredentialResponse_Encoding = 1
	CredentialResponse_BASE64               CredentialResponse_Encoding = 2
	CredentialResponse_BASE64URL            CredentialResponse_Encoding = 3
)

// Enum value maps for CredentialResponse_Encoding.
var (
	CredentialResponse_Encoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "UTF8",
		2: "BASE64",
		3: "BASE64URL",
	}
	CredentialResponse_Encoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"UTF8":                 1,
		"BASE64":               2,
		"BASE64URL":            3,
	}
)

func (x CredentialResponse_Encoding) Enum() *CredentialResponse_Encoding {
	p := new(CredentialResponse_Encoding)
	*p = x
	return p
}

func (x CredentialResponse_Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialResponse_Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes[1].Descriptor()
}

func (CredentialResponse_Encoding) Type() protoreflect.EnumType {
	return &file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes[1]
}

func (x CredentialResponse_Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialResponse_Encoding.Descriptor instead.
func (CredentialResponse_Encoding) EnumDescriptor() ([]byte, []int) {
	return file_pkg_credentialprovider_v1_credential_provider_proto_rawDescGZIP(), []int{1, 1}
}

// CredentialRequest is written as one protobuf message to provider stdin.
type CredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRequest) Reset() {
	*x = CredentialRequest{}
	mi := &file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRequest) ProtoMessage() {}

func (x *CredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRequest.ProtoReflect.Descriptor instead.
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return file_pkg_credentialprovider_v1_credential_provider_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *CredentialRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// CredentialResponse is read as one protobuf message from provider stdout.
type CredentialResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ApiVersion    string                      `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Status        CredentialResponse_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=opensandbox.egress.credentialprovider.v1.CredentialResponse_Status" json:"status,omitempty"`
	Credential    []byte                      `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	Encoding      CredentialResponse_Encoding `protobuf:"varint,4,opt,name=encoding,proto3,enum=opensandbox.egress.credentialprovider.v1.CredentialResponse_Encoding" json:"encoding,omitempty"`
	ExpiresAt     *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Cacheable     bool                        `protobuf:"varint,6,opt,name=cacheable,proto3" json:"cacheable,omitempty"`
	ErrorCode     string                      `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialResponse) Reset() {
	*x = CredentialResponse{}
	mi := &file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialResponse) ProtoMessage() {}

func (x *CredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialResponse.ProtoReflect.Descriptor instead.
func (*CredentialResponse) Descriptor() ([]byte, []int) {
	return file_pkg_credentialprovider_v1_credential_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *CredentialResponse) GetStatus() CredentialResponse_Status {
	if x != nil {
		return x.Status
	}
	return CredentialResponse_STATUS_UNSPECIFIED
}

func (x *CredentialResponse) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CredentialResponse) GetEncoding() CredentialResponse_Encoding {
	if x != nil {
		return x.Encoding
	}
	return CredentialResponse_ENCODING_UNSPECIFIED
}

func (x *CredentialResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CredentialResponse) GetCacheable() bool {
	if x != nil {
		return x.Cacheable
	}
	return false
}

func (x *CredentialResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_pkg_credentialprovider_v1_credential_provider_proto protoreflect.FileDescriptor

const file_pkg_credentialprovider_v1_credential_provider_proto_rawDesc = "" +
	"\n" +
	"3pkg/credentialprovider/v1/credential_provider.proto\x12(opensandbox.egress.credentialprovider.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x11CredentialRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"\xa4\x04\n" +
	"\x12CredentialResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12[\n" +
	"\x06status\x18\x02 \x01(\x0e2C.opensandbox.egress.credentialprovider.v1.CredentialResponse.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\fR\n" +
	"credential\x12a\n" +
	"\bencoding\x18\x04 \x01(\x0e2E.opensandbox.egress.credentialprovider.v1.CredentialResponse.EncodingR\bencoding\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1c\n" +
	"\tcacheable\x18\x06 \x01(\bR\tcacheable\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\"J\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x02\x12\n" +
	"\n" +
	"\x06DENIED\x10\x03\"I\n" +
	"\bEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04UTF8\x10\x01\x12\n" +
	"\n" +
	"\x06BASE64\x10\x02\x12\r\n" +
	"\tBASE64URL\x10\x03BVZTgithub.com/alibaba/opensandbox/egress/pkg/credentialprovider/v1;credentialproviderv1b\x06proto3"

var (
	file_pkg_credentialprovider_v1_credential_provider_proto_rawDescOnce sync.Once
	file_pkg_credentialprovider_v1_credential_provider_proto_rawDescData []byte
)

func file_pkg_credentialprovider_v1_credential_provider_proto_rawDescGZIP() []byte {
	file_pkg_credentialprovider_v1_credential_provider_proto_rawDescOnce.Do(func() {
		file_pkg_credentialprovider_v1_credential_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_credentialprovider_v1_credential_provider_proto_rawDesc), len(file_pkg_credentialprovider_v1_credential_provider_proto_rawDesc)))
	})
	return file_pkg_credentialprovider_v1_credential_provider_proto_rawDescData
}

var file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_credentialprovider_v1_credential_provider_proto_goTypes = []any{
	(CredentialResponse_Status)(0),   // 0: opensandbox.egress.credentialprovider.v1.CredentialResponse.Status
	(CredentialResponse_Encoding)(0), // 1: opensandbox.egress.credentialprovider.v1.CredentialResponse.Encoding
	(*CredentialRequest)(nil),        // 2: opensandbox.egress.credentialprovider.v1.CredentialRequest
	(*CredentialResponse)(nil),       // 3: opensandbox.egress.credentialprovider.v1.CredentialResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_pkg_credentialprovider_v1_credential_provider_proto_depIdxs = []int32{
	0, // 0: opensandbox.egress.credentialprovider.v1.CredentialResponse.status:type_name -> opensandbox.egress.credentialprovider.v1.CredentialResponse.Status
	1, // 1: opensandbox.egress.credentialprovider.v1.CredentialResponse.encoding:type_name -> opensandbox.egress.credentialprovider.v1.CredentialResponse.Encoding
	4, // 2: opensandbox.egress.credentialprovider.v1.CredentialResponse.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_credentialprovider_v1_credential_provider_proto_init() }
func file_pkg_credentialprovider_v1_credential_provider_proto_init() {
	if File_pkg_credentialprovider_v1_credential_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_credentialprovider_v1_credential_provider_proto_rawDesc), len(file_pkg_credentialprovider_v1_credential_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_credentialprovider_v1_credential_provider_proto_goTypes,
		DependencyIndexes: file_pkg_credentialprovider_v1_credential_provider_proto_depIdxs,
		EnumInfos:         file_pkg_credentialprovider_v1_credential_provider_proto_enumTypes,
		MessageInfos:      file_pkg_credentialprovider_v1_credential_provider_proto_msgTypes,
	}.Build()
	File_pkg_credentialprovider_v1_credential_provider_proto = out.File
	file_pkg_credentialprovider_v1_credential_provider_proto_goTypes = nil
	file_pkg_credentialprovider_v1_credential_provider_proto_depIdxs = nil
}
